model_name: 'mistralai/Mistral-7B-Instruct-v0.3'
dataset: 'ade'
train_steps: 5
epochs: 1
batch_size_train: 8
batch_size_eval: 4
grad_acc_steps: 1
lr: 2e-4
max_length: 4096
n_icl_samples: 3
dtype: None
rationale: 'entity2type.json'
entitytypes: 'code_prompt'
prompt_filename: 'q-k-v-o-gate-up-down'
target_modules: 0
val: 1
save_model: 0
save_results: 0
val_samples: 0
load_in_4bit: 0
load_in_8bit: 0
chat: 0
natlang: 0
verbose_train: 0
seed: 0